// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqpyfzOZcXD3MJ7tpodNirNfDSCIDTHM4',
    appId: '1:792271876683:web:8093ef1dbd44de456953ce',
    messagingSenderId: '792271876683',
    projectId: 'todolist2025-50650',
    authDomain: 'todolist2025-50650.firebaseapp.com',
    storageBucket: 'todolist2025-50650.firebasestorage.app',
    measurementId: 'G-V3W4LRZZP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvxEvuRrkkTpcsujpBerdbo7gVkTVN4U',
    appId: '1:792271876683:android:974fb2c2793ab7cd6953ce',
    messagingSenderId: '792271876683',
    projectId: 'todolist2025-50650',
    storageBucket: 'todolist2025-50650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQBWYnB_kgRHOiv-PwqDpvn19AdG2-_w8',
    appId: '1:792271876683:ios:efd04d9b629760266953ce',
    messagingSenderId: '792271876683',
    projectId: 'todolist2025-50650',
    storageBucket: 'todolist2025-50650.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQBWYnB_kgRHOiv-PwqDpvn19AdG2-_w8',
    appId: '1:792271876683:ios:efd04d9b629760266953ce',
    messagingSenderId: '792271876683',
    projectId: 'todolist2025-50650',
    storageBucket: 'todolist2025-50650.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqpyfzOZcXD3MJ7tpodNirNfDSCIDTHM4',
    appId: '1:792271876683:web:2d8d9218cbf034ba6953ce',
    messagingSenderId: '792271876683',
    projectId: 'todolist2025-50650',
    authDomain: 'todolist2025-50650.firebaseapp.com',
    storageBucket: 'todolist2025-50650.firebasestorage.app',
    measurementId: 'G-KNZPC8YRWC',
  );
}
